In [1]:
import numpy as np


In [3]:
a = np.zeros(10)
a[4] = 1

In [4]:
ndarray = np.arange(10,50)

In [5]:
ndarray = ndarray[::-1]

In [6]:
b = np.random.random(size=(10,10))

In [17]:
c = np.zeros((10,10))
c[:,0] = 1
c[:,-1] = 1
c[0] = 1
c[-1] = 1
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.array([0,1,2,3,4]*5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [28]:
d = np.random.randint(10,size = 10)
d

array([4, 7, 3, 4, 0, 7, 8, 1, 7, 2])

In [35]:
d.max()
c = d == d.max()
d[c] = -10
d

array([  4, -10,   3,   4,   0, -10, -10,   1, -10,   2])

In [36]:
v_min = d.min()

In [39]:
e = np.argwhere(d == v_min)

In [41]:
d[e] = 100
d

array([  4, 100,   3,   4,   0, 100, 100,   1, 100,   2])

In [56]:
nd3 = np.random.randint(150,size=(5,5))
nd3

array([[ 59, 130,   5, 138,   0],
       [ 99,  28, 118,  89,  11],
       [ 32,  78,  78, 107,  53],
       [ 30, 107, 115,  46,   1],
       [  1, 115, 117, 115,  79]])

In [57]:
nd3[[1,3,4,0,2]]


array([[ 99,  28, 118,  89,  11],
       [ 30, 107, 115,  46,   1],
       [  1, 115, 117, 115,  79],
       [ 59, 130,   5, 138,   0],
       [ 32,  78,  78, 107,  53]])

In [55]:
nd3.sum(axis = 1).sum()

1708

In [66]:
nd = np.zeros((8,8))

In [75]:
nd = np.zeros((8,8))
nd[1::2,::2] = 1
nd[::2,1::2] = 1
nd

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
s =