In [2]:
#K临近算法
#KNN
#欧几里得距离
#SKLEARN的数据必须是二维的
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [8]:
movie = pd.read_excel('./maishu/movie.xlsx')
movie

电影名称  武打镜头  接吻镜头 分类情况
0   大话西游    36     1  动作片
1    杀破狼    43     2  动作片
2    前任3     0    10  爱情片
3    战狼2    59     1  动作片
4  泰坦尼克号     1    15  爱情片
5   星语心愿     2    19  爱情片

In [13]:
X = movie[['武打镜头','接吻镜头']]
X
Y = movie['分类情况']
Y

0    动作片
1    动作片
2    爱情片
3    动作片
4    爱情片
5    爱情片
Name: 分类情况, dtype: object

In [15]:
knn = KNeighborsClassifier(n_neighbors=5)

#该方法就是训练数据
knn.fit(X,Y)

KNeighborsClassifier()

In [18]:
#预测新电影
#碟中谍6 100，10
#战狼2 200 1
#色戒 0 10
X_test = pd.DataFrame({'武打镜头':[100,200,0],'接吻镜头':[10,1,10]})

In [19]:
knn.predict(X_test)

array(['动作片', '动作片', '爱情片'], dtype=object)

In [21]:
knn.predict_proba(X_test)

array([[0.6, 0.4],
       [0.6, 0.4],
       [0.4, 0.6]])

In [22]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)

#身高、体重、鞋的尺寸

X = np.array([[181,80,44],[177,70,43],[160,60,38],[154,54,37],

     [166,65,40],[190,90,47],[175,64,39],[177,70,40],

     [159,55,37],[171,75,42],[181,85,43]])

display(X)

y = ['male','male','female','female','male','male','female','female','female','male','male']

# 第1步：训练数据

neigh.fit(X,y)

# 第2步：预测数据

Z = neigh.predict(np.array([[190,70,43],[168,55,37]]))

display(Z)

array([[181,  80,  44],
       [177,  70,  43],
       [160,  60,  38],
       [154,  54,  37],
       [166,  65,  40],
       [190,  90,  47],
       [175,  64,  39],
       [177,  70,  40],
       [159,  55,  37],
       [171,  75,  42],
       [181,  85,  43]])

array(['male', 'female'], dtype='<U6')

In [23]:
np.random.randint(0,300,size=300)

array([136,  11, 256,  38, 206,  83, 269, 120, 245, 283, 233,  90, 298,
       212, 138,  16, 147, 230, 241, 130, 117, 254, 113, 105, 167, 225,
       105, 184,  97, 219, 225, 276,  60,  80, 256,  23,  56, 175, 158,
       232, 175,   9,  34,  20, 254, 216,  35,  93,  40,  99,  42, 283,
       286,  52,  41, 135,  81, 247,  85, 222,  34, 209, 293,  35, 124,
       255, 193, 166,  32,  84, 259, 262, 188, 215,  85, 113, 218,  96,
        67, 297, 189, 274, 202, 252, 275, 221, 122, 139,  34,   9, 198,
        75, 111, 183,  33,  12, 112, 180, 195,  17,  24, 271,  34, 245,
        90, 173,   3, 236,  49, 152, 296, 189, 102, 235, 298,  80,  26,
       272, 102, 258, 159, 217,  17,  43,  74, 278, 191, 203, 139, 183,
       243,  20, 256, 178,  57, 246, 125, 165, 250,   4, 180, 181, 140,
       171,  90, 193,  54,   0, 207, 268, 284, 180, 268, 214,  54,  27,
       208, 231,  87, 230,  17, 257, 215, 236, 286, 265,  94, 281, 165,
       236, 225, 250, 218,  94, 179,  93, 287, 126, 175, 191, 20