In [17]:
#线性回归评价指标 lr.score()

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import sklearn.datasets as datasets

In [2]:
diabetes = datasets.load_diabetes()

In [3]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = diabetes['data']
y = diabetes['target']

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [8]:
#数据经过了处理，因为有正有负，经过了归一化处理
X_train

array([[ 0.03081083,  0.05068012, -0.03422907, ...,  0.05755657,
         0.03546194,  0.08590655],
       [ 0.02354575,  0.05068012, -0.03961813, ..., -0.03949338,
        -0.10164355, -0.06735141],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643322, -0.01764613],
       ...,
       [ 0.03807591,  0.05068012,  0.00564998, ...,  0.03430886,
         0.01482271,  0.06105391],
       [ 0.03807591,  0.05068012, -0.00943939, ...,  0.05017634,
        -0.02595242,  0.10661708],
       [ 0.00538306, -0.04464164,  0.04984027, ..., -0.00259226,
         0.01703713, -0.01350402]])

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
lr.predict(X_test).round(2)

array([ 59.61,  80.49, 128.54, 123.96,  75.85, 120.76, 190.8 , 135.09,
        86.04, 140.54, 274.91,  76.05, 124.34, 251.71, 165.84, 195.99,
       217.2 ,  99.43,  76.31,  59.88, 198.62,  60.12, 177.39, 139.35,
       140.32,  98.09, 157.28, 259.1 ,  60.91,  99.34, 201.68, 140.27,
        79.05, 261.95, 183.34, 205.13, 163.97, 179.56, 119.69,  95.65,
       170.32, 183.89, 199.1 ,  63.59, 157.11, 176.41, 125.86, 122.17,
       234.12, 163.75, 229.93,  49.3 , 137.05, 172.79, 170.48, 231.7 ,
        92.3 ,  60.18, 122.45, 171.17, 197.72,  77.66, 192.31,  85.41,
       223.94, 149.35, 177.92, 121.93, 129.15, 147.13,  65.77, 108.85,
       103.6 , 144.65, 228.56, 143.36, 218.39, 166.12, 155.76, 119.42,
       204.7 , 160.27,  76.51, 229.35,  84.83, 165.12, 100.85, 150.83,
       102.31])

In [16]:
lr.score(X_test,y_test)

0.5363321904564924

In [14]:
y_test

array([ 77.,  72.,  65., 178., 138.,  63., 229.,  60.,  71., 116., 243.,
        89.,  97., 336., 151., 292., 173.,  72.,  92.,  85., 221.,  70.,
        66., 230., 142., 125., 237., 245.,  52., 118., 248., 172.,  98.,
       263.,  78., 265., 265., 124., 127.,  65., 147., 175., 220.,  43.,
       100.,  91.,  84., 150., 217., 109., 261.,  65., 182., 138., 174.,
       321., 115.,  52.,  66., 111., 241., 200., 129.,  87., 248.,  85.,
       262., 145.,  42., 202.,  72., 142., 109., 136., 152.,  50., 332.,
       206., 198., 153., 292., 104.,  60., 232., 102., 128., 101., 246.,
        47.])